### ISSUE TITLE
volume creation will fail if <2016-3-0

### ISSUE THREAD

**Issue by epcim** [tcpcloud/salt-formula-glusterfs#4]
https://github.com/tcpcloud/salt-formula-glusterfs/blob/master/glusterfs/server/setup.sls#L3

fix the the if should compare <2016.3.0

**Comment by hoffmannliu-ayla** [comment]
I am curious of this kind of comparison. I don't really know how Jinja would interpret this kind of string comparison: is  '2016.11.3'  really greater or less than '2016.3.0' or '2015.8.0' ? I am using 2016.11.3 and it always sets force_compatiblity to True. 

I would suggest we use "grains['saltversioninfo']" list instead. Though it is not fancy, but it should work. Like this:
{%- if grains['saltversioninfo'][0] < 2016 %}
.....
{%- elif grains['saltversioninfo'][1] < 3 %}
....
{%- else %}
....
{%- endif %}

**Comment by fpytloun** [comment]
@hoffmannliu-ayla yes, I agree that's better approach. Using it to fix the issue.. ;-)
